### ISSUE TITLE
Server crashes after leaving it

### ISSUE THREAD

**Issue by Sereath** [Un-Original1/Deep-Below#1]
https://mclo.gs/lJNvPUd

```
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: com/unoriginal/mimicfish/MimicfishClientHandler
    at com.unoriginal.mimicfish.chest_searcher.Controller.drawOres(Controller.java:41)
    at com.unoriginal.mimicfish.chest_searcher.Controller.requestBlockFinder(Controller.java:91)
    at com.unoriginal.mimicfish.chest_searcher.Controller.toggleDrawOres(Controller.java:49)
    at com.unoriginal.mimicfish.init.ModEvents.onPlayerLogOut(ModEvents.java:92)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1412_ModEvents_onPlayerLogOut_PlayerLoggedOutEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.fml.common.FMLCommonHandler.firePlayerLoggedOut(FMLCommonHandler.java:580)
    at net.minecraft.server.management.PlayerList.playerLoggedOut(PlayerList.java:388)
    at net.minecraft.network.NetHandlerPlayServer.onDisconnect(NetHandlerPlayServer.java:853)
    at net.minecraft.network.NetworkManager.handleDisconnection(NetworkManager.java:457)
    at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:213)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:790)
    at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: com.unoriginal.mimicfish.MimicfishClientHandler
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 17 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer@673919a7 from coremod FMLCorePlugin
    at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:260)
    at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
    ... 19 more
Caused by: java.lang.RuntimeException: Attempted to load class com/unoriginal/mimicfish/MimicfishClientHandler for invalid side SERVER
    at net.minecraftforge.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:62)
    at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:256)
    ... 21 more
```
```
  Suspected Mods: Deep Below (mimicfish), Forge Mod Loader (FML), Minecraft Forge (forge)
```

**Comment by Un-Original1** [comment]
Oops. I suppose this is what happens when I mess too much with logical sides, I'll try to fix it asap.

**Comment by Un-Original1** [comment]
It should be fixed with the latest release. Make shure to tell me if it worked so I can close this issue.

**Comment by Sereath** [comment]
I'll try it as soon as I can.

**Comment by Sereath** [comment]
It seems good now.
